// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opskocsynccehimnmaxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wc2tvY3N5bmNjZWhpbW5tYXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDUyMDIsImV4cCI6MjA1MzIyMTIwMn0.caU0viTKu3Mk9J6WCguoMy5eh1sKJ4TCFvZfPEU29G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);